name: AutoBashed Semantic Versioning (SemVer) for RELEASE and SNAPSHOT
description: Generate Semantic Version based on Conventional Commit, update whatever.json and bump Tag, via Bash
branding:
  icon: repeat
  color: green

inputs:
  bump-tag:
    description: 'Bump Tag to Git repository'
    required: false
    default: 'true'
  file-update:
    description: 'Updates file with new semver and add change to last commit'
    required: false
    default: 'true'
  file-path:
    description: 'File path to update (JSON ONLY)'
    required: false
    default: 'package.json'
  major:
    description: 'Wording for MAJOR'
    required: false
    default: 'BREAKING'
  minor:
    description: 'Wording for MINOR'
    required: false
    default: 'feat'
  prefix:
    description: 'Set a prefix to your tag'
    required: false
    default: ''
  enable-snapshot:
    description: 'Generate SNAPSHOT instead of RELEASE'
    required: false
    default: 'false'
  snapshot-suffix:
    description: 'Suffix for SNAPSHOT version (e.g: 1.0.1-SNAPSHOT)'
    required: false
    default: 'SNAPSHOT'

outputs:
  semver:
    description: 'Next generated SemVer as string'
    value: ${{ steps.autobashed-semver.outputs.semver }}

runs:
  using: 'composite'
  steps:
    - id: autobashed-semver
      run: ${{ github.action_path }}/autobashed-semver
      shell: bash
      env:
        INPUT_BUMP_TAG: '${{ inputs.bump-tag }}'
        INPUT_FILE_UPDATE: '${{ inputs.file-update }}'
        INPUT_FILE_PATH: '${{ inputs.file-path }}'
        INPUT_MAJOR: '${{ inputs.major }}'
        INPUT_MINOR: '${{ inputs.minor }}'
        INPUT_PREFIX: '${{ inputs.prefix }}'
        INPUT_ENABLE_SNAPSHOT: '${{ inputs.enable-snapshot }}'
        INPUT_SNAPSHOT_SUFFIX: '${{ inputs.snapshot-suffix }}'
